version: '3.8'

services:
  confluence-citizen:
    build: .
    container_name: confluence-citizen
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      - KAFKA_BROKERS=kafka:9093
    networks:
      - project-manager-network
    restart: unless-stopped

networks:
  project-manager-network:
    external: true
